export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"
export const LOG_OUT_REQUEST = "LOG_OUT_REQUEST"
export const LOG_OUT_SECCESS = "LOG_OUT_SECCESS"
export const LOG_OUT_FAILURE = "LOG_OUT_FAILURE"


